apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
  namespace: test-server
  labels:
    app: test-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
      - name: test-server
        image: waynr/test-server:0.4.3
        command:
          - /usr/bin/test-server
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

