apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "120"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "6"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "10"
  name: test-server
  namespace: test-server
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: test-server
