{
 "title": "INCI-1069",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_region",
    "query": {
     "query": "label_values(testserver_http_connections_duration_s_count,source_region)"
    }
   },
   {
    "name": "destination_region",
    "query": {
     "query": "label_values(testserver_http_connections_duration_s_count,region)"
    }
   },
   {
    "name": "result_type",
    "query": {
     "query": "label_values(testserver_http_connections_duration_s_count,result_type)"
    }
   },
   {
    "name": "content_length",
    "query": {
     "query": "label_values(testserver_http_connections_duration_s_count,content_length)"
    }
   }
  ]
 },
 "panels": [
  { "title": "summary: all-to-all regions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(testserver_http_connections_duration_s_bucket{content_length=~\"$content_length\",result_type=~\"$result_type\"}[5m])) by (le))",
     "legendFormat": "p99 duration"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(testserver_http_connections_duration_s_bucket{content_length=~\"$content_length\",result_type=~\"$result_type\"}[5m])) by (le))",
     "legendFormat": "p99 duration"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(testserver_http_connections_duration_s_bucket{content_length=~\"$content_length\",result_type=~\"$result_type\"}[5m])) by (le))",
     "legendFormat": "p99 duration"
    }
   ]
  },
  {
   "title": "request rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(testserver_http_connections_duration_s_count{content_length=~\"$content_length\",result_type=~\"$result_type\"}[10m])) by (result_type)",
     "legendFormat": "{{result_type}}"
    }
   ]
  },
  {
   "title": "request duration (source: $source_region)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "source_region"
  },
  {
   "title": "$destination_region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2.6666666666666665, "x": 0, "y": 10 },
   "repeat": "destination_region",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(testserver_http_connections_duration_s_bucket{source_region=~\"$source_region\",region=~\"$destination_region\",content_length=~\"$content_length\",result_type=~\"$result_type\"}[10m])) by (le))",
     "legendFormat": "p99 duration"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(testserver_http_connections_duration_s_bucket{source_region=~\"$source_region\",region=~\"$destination_region\",content_length=~\"$content_length\",result_type=~\"$result_type\"}[10m])) by (le))",
     "legendFormat": "p90 duration"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(testserver_http_connections_duration_s_bucket{source_region=~\"$source_region\",region=~\"$destination_region\",content_length=~\"$content_length\",result_type=~\"$result_type\"}[10m])) by (le))",
     "legendFormat": "p50 duration"
    }
   ]
  },
  {
   "title": "request rate: (source: $source_region)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "repeat": "source_region"
  },
  {
   "title": "$source_region to $destination_region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 100 },
   "repeat": "destination_region",
   "targets": [
    {
     "expr": "sum(rate(testserver_http_connections_duration_s_count{source_region=~\"$source_region\",region=~\"$destination_region\"}[1m])) by (result_type)",
     "legendFormat": "{{result_type}}"
    }
   ]
  }
 ]
}