name: release

env:
  GITHUB_TOKEN: ${{ secrets.GHCRTOKEN }}

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          fetch-depth: 1

      - name: build image
        run: docker build --platform linux/amd64 -t ghcr.io/digitalocean-packages/doks-debug:latest .

      - name: push image
        run: docker push ghcr.io/digitalocean-packages/doks-debug:latest
